-d C:\Project\gowin_fpga\github_project\i2c\i2c_write_one_command_no_parameter_same_clk\impl\gwsynthesis\i2c_write_one_command_no_parameter_same_clk.vg
-p GW1NR-9C-QFN88P-6
-pn GW1NR-LV9QN88PC6/I5
-cst C:\Project\gowin_fpga\github_project\i2c\i2c_write_one_command_no_parameter_same_clk\src\i2c_write_test_1.cst
-cfg C:\Project\gowin_fpga\github_project\i2c\i2c_write_one_command_no_parameter_same_clk\impl\pnr\device.cfg
-gao_crc 1101010000011000
-bit
-tr
-ph
-timing
-cst_error
-convert_sdp32_36_to_sdp16_18
-place_option 0
-route_option 0
-clock_route_order 0
-correct_hold 1
-route_maxfan 23
-global_freq 50.000
-rtl_gao
